name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: [ "mac-mini", "mac", "macos" ]
    env:
      ANDROID_HOME: /Users/zz/Library/Android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #      - name: Set up JDK 17
      #        uses: actions/setup-java@v4
      #        with:
      #          distribution: 'zulu'
      #          java-version: 17
      #
      #      - name: Setup Gradle
      #        uses: gradle/actions/setup-gradle@v4
      #        with:
      #          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      #      - name: Setup Android SDK
      #        uses: android-actions/setup-android@v3
      #
      #      - name: Accept licenses
      #        run: yes | sdkmanager --licenses || true

      - name: Run linting
        run: |
          ./scripts/lint.sh

      - name: Run tests
        run: |
          ./scripts/test.sh -u
